<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGI7heZE\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGI7heZE/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGI7heZE.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGI7heZE\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGI7heZE\appAppKernelProdContainer([
    'container.build_hash' => 'GI7heZE',
    'container.build_id' => 'a0e2d644',
    'container.build_time' => 1720693782,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGI7heZE');
