<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2TEC6kj+ScbWy88EsNiI'."\n".'qX0xuNElEXo5kWYT0Xm5IxEHw/foKI3PLuCqQwbg/Ka/QHwosq3hjTxUQHhUEPKm'."\n".'KZdE3g0KuBMEedDtiBveB001Fd2pJ+ht1dGM+CHZ7IvlRpd8CXZEjZgoOvz/8E3Z'."\n".'JJjy/5tHEFw+FLWyGNwGBneJgj4Lwv4FyaFJ8CG8y6FdOGSOudOz1iVjxx3ml5hJ'."\n".'/TBbKvuIkQLDqTnBA3LHP0q2saoOhruqvJyww81kL1/6WewkMozWVB5M7PT3xFmG'."\n".'EkQNNP7ylDbIDYNnC3Xgfqs87poh08OrN6dDotLL5m52/I9WRBmlS8oLQsCRFFGw'."\n".'KwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
