<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV88xsLU\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV88xsLU/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV88xsLU.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV88xsLU\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerV88xsLU\appAppKernelDevDebugContainer([
    'container.build_hash' => 'V88xsLU',
    'container.build_id' => '69b747c8',
    'container.build_time' => 1721219372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV88xsLU');
