<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD4l6Dqx\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD4l6Dqx/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD4l6Dqx.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD4l6Dqx\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerD4l6Dqx\appAppKernelDevDebugContainer([
    'container.build_hash' => 'D4l6Dqx',
    'container.build_id' => '604c5d42',
    'container.build_time' => 1721303346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD4l6Dqx');
